# Generated by Django 3.1.3 on 2023-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20201209_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
